version: '3' 

services:
  # 后端服务
  backend:
    depends_on:
      - database
    build: 
      context: ./services/backend 
    ports:
      - "8001:3000"
    links:
      - database
    volumes:
      - ./services/backend:/var/trace-proj
    networks:
      - trace-network
    restart: on-failure
    command: ["/wait-for-it.sh", "database:8002", "--", "gunicorn", "-w", "4", "-b", "0.0.0.0:3000", "--forwarded-allow-ips='nginx'", "wsgi:server"]


  # 数据库服务
  database: 
    build: ./services/database
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD=Trace.Social-2021
      - MYSQL_DATABASE=trace_db
    ports:
      - "8002:3306" 
    networks:
      - trace-network
    volumes:
      - ./services/database:/docker-entrypoint-initdb.d
      - trace-volume:/var/lib/mysql

  # 负载均衡
  # nginx: 
  #   depends_on:
  #     - backend
  #   image: nginx:1.20-alpine
  #   networks:
  #     - trace-network
  #   ports: 
  #     - "80:80"
  #   volumes:
  #     - ./services/nginx:/var/trace-proj
  #     - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   restart: on-failure

# 存储卷配置
volumes:
  trace-volume:

# 定义网络
networks:
  trace-network: 
